### ISSUE TITLE
kontrolki

### ISSUE THREAD

**Issue by domel** [JakubTederko/service-github.io#11]
https://github.com/JakubTederko/service-github.io/blob/0b302d2481a876b18666ca727c0ea06c1ab420a1/MA_Warsztaty.html#L62-L82

To jest jakies krzywe, prosze dodac odpowiednie klasy

**Comment by Ziemek93** [comment]
Chodzi o przycisk dropmenu, że jest troche poniżej??

**Comment by domel** [comment]
tak
